### ISSUE TITLE
Problem of compatibility with Serial 6.0.0

### ISSUE THREAD

**Issue by kabej** [lunarok/jeedom_mySensors#14]
Impossible to instanciate SerialPort with **baudrate** options (lower case)

```
var SerialPort = require('serialport');
        gw = new SerialPort(gwAddress, { baudrate: 115200 });
        //compatibilité avec la nouvelle verion de serialport
        if ( gw.settings.baudRate ){
                gw.settings.baudRate=115200;
        }
```

```
/var/www/html/plugins/mySensors/node/node_modules/serialport/lib/serialport.js:127
throw new TypeError(`"baudrate" is an unknown option, did you mean "baudRate"?`);
^
TypeError: "baudrate" is an unknown option, did you mean "baudRate"?
at new SerialPort (/var/www/html/plugins/mySensors/node/node_modules/serialport/lib/serialport.js:127:11)
at launchGateway (/var/www/html/plugins/mySensors/node/mysensors.js:230:9)
at Object.<anonymous> (/var/www/html/plugins/mySensors/node/mysensors.js:319:1)
at Module._compile (module.js:435:26)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Function.Module.runMain (module.js:467:10)
at startup (node.js:134:18)
at node.js:961:3
```

**Comment by lunarok** [comment]
https://github.com/lunarok/jeedom_mySensors/commit/d2f912e77c47578f1680111ccf789edb9776a09c

**Comment by kabej** [comment]
Not working on last version Serial 6.0.0 out few days ago (2017-10-09) 

Work with #15

**Comment by kabej** [comment]
See https://github.com/EmergingTechnologyAdvisors/node-serialport/commit/a3b8d35
